series: Basic OpenGL with GLFW
title: Object Loading
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Load mesh information from an obj file.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Materials
  - series: Basic OpenGL with GLFW
    title: Basic Lighting